language: node_js

node_js:
    - "6"
    - "node"
sudo: false
before_install:
    - npm install -g eslint
    - npm install -g istanbul
install:
    - npm install
script:
    - npm run compile
    - npm run coverage
    - npm run browserify
